name = "audio-ai-mab-worker"
main = "src/index.js"
compatibility_date = "2024-03-20"

[triggers]
crons = ["0 * * * *"] # Run every hour

[[d1_databases]]
binding = "DB"
database_name = "audio-db"
database_id = "478ffd20-05b6-4381-a863-d88508e8c87e"

# [vars]
# GEMINI_API_KEY = "..."
